# Generated by Django 3.1.3 on 2020-11-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
