# Generated by Django 3.1.3 on 2020-11-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
    ]
