# Generated by Django 3.1.3 on 2020-11-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
